<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 car.glb
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-muscle-car-641efc889e5f4543bae51d0922e6f4b3
Title: Classic Muscle car
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/car.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={[1, 0.85, 5.95]}>
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.Material} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['Material.003']} />
      <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials['Material.004']} />
      <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials['Material.005']} />
      <T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials['Material.006']} />
      <T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials['Material.007']} />
      <T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials['Material.008']} />
    </T.Group>
    <T.Group position={[-2.23, -0.63, 3.82]}>
      <T.Mesh geometry={gltf.nodes.Object_13.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Object_15.geometry} material={gltf.materials['Material.007']} />
    </T.Group>
    <T.Group position={[2.23, -0.53, -3.08]}>
      <T.Mesh geometry={gltf.nodes.Object_17.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Object_19.geometry} material={gltf.materials['Material.007']} />
    </T.Group>
    <T.Group position={[2.23, -0.63, 3.82]}>
      <T.Mesh geometry={gltf.nodes.Object_21.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_22.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Object_23.geometry} material={gltf.materials['Material.007']} />
    </T.Group>
    <T.Group position={[-2.23, -0.53, -3.08]}>
      <T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Object_27.geometry} material={gltf.materials['Material.007']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
