<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 truck.glb
Author: PolyDucky (https://sketchfab.com/salphytheunemployed)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-truck-d4bcb5ab731948bbabc2e9fe976cc0f2
Title: Low Poly Truck
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/truck.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.52}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.Lights} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials['Material.003']} />
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['Material.004']} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.Screen} />
      <T.LineSegments geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.TruckBlack} />
      <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials.Grey} />
      <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.TruckBlack} />
      <T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.TruckWhiteBody} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
