<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 C:\Users\hunor\OneDrive\Documents\Programozás\bosch\static\models\truck.glb --root /models/ --printwidth 120 --precision 2
Author: ROY (https://sketchfab.com/roy.gearloft.in)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/truck-eda924f23ba04cd5b1e5160abf2320fa
Title: Truck
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/truck.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene" position.y={2.3}>
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 3.14]} scale={0.77}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Empty010_13" position={[1.35, -2.08, -4.31]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle028_11"
                position={[-0.18, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_44"
                  geometry={gltf.nodes.Object_44.geometry}
                  material={gltf.materials['tyres.011']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle029_12"
                position={[-0.29, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_46"
                  geometry={gltf.nodes.Object_46.geometry}
                  material={gltf.materials['wheels.011']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Empty009_16" position={[-1.35, -2.08, -4.31]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle024_14"
                position={[0.29, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_49"
                  geometry={gltf.nodes.Object_49.geometry}
                  material={gltf.materials['wheels.009']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle025_15"
                position={[0.18, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_51"
                  geometry={gltf.nodes.Object_51.geometry}
                  material={gltf.materials['tyres.009']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Empty001_19" position={[1.08, -2.08, 3.18]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle009_17"
                position={[-0.22, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_54"
                  geometry={gltf.nodes.Object_54.geometry}
                  material={gltf.materials['wheels.003']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle010_18"
                position={[-0.16, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_56"
                  geometry={gltf.nodes.Object_56.geometry}
                  material={gltf.materials['tyres.003']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Empty006_22" position={[1.08, -2.08, 5.35]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle006_20"
                position={[-0.16, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_59"
                  geometry={gltf.nodes.Object_59.geometry}
                  material={gltf.materials['tyres.012']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle007_21"
                position={[-0.22, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_61"
                  geometry={gltf.nodes.Object_61.geometry}
                  material={gltf.materials['wheels.012']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Empty007_25" position={[-1.08, -2.08, 3.18]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle008_23"
                position={[0.15, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_64"
                  geometry={gltf.nodes.Object_64.geometry}
                  material={gltf.materials['tyres.013']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle012_24"
                position={[0.22, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_66"
                  geometry={gltf.nodes.Object_66.geometry}
                  material={gltf.materials['wheels.013']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Empty008_28" position={[-1.08, -2.08, 5.35]} scale={[1.73, 2.26, 2.26]}>
              <T.Group
                name="wheels_Circle013_26"
                position={[0.16, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_69"
                  geometry={gltf.nodes.Object_69.geometry}
                  material={gltf.materials['tyres.014']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle014_27"
                position={[0.22, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_71"
                  geometry={gltf.nodes.Object_71.geometry}
                  material={gltf.materials['wheels.014']}
                />
              </T.Group>
            </T.Group>
            <T.Group name="Truck_4" rotation={[-Math.PI, 0, -Math.PI]} scale={[2.26, 3.03, 10.44]}>
              <T.Group
                name="Empty_2"
                position={[0, -0.6, 0.57]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.75, 0.56, 0.16]}
              >
                <T.Group name="Cylinder_0" position={[0, 0.37, 0]} scale={[0.09, 0.34, 0.09]}>
                  <T.Mesh
                    name="Object_6"
                    geometry={gltf.nodes.Object_6.geometry}
                    material={gltf.materials.material_0}
                  />
                </T.Group>
                <T.Group
                  name="Truck_head_Truck_headL_1"
                  position={[0.02, 0.75, -1.83]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                  scale={1.34}
                >
                  <T.Mesh
                    name="Object_8"
                    geometry={gltf.nodes.Object_8.geometry}
                    material={gltf.materials.head_paint}
                  />
                  <T.Mesh name="Object_9" geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.glass} />
                  <T.Mesh
                    name="Object_10"
                    geometry={gltf.nodes.Object_10.geometry}
                    material={gltf.materials.full_glossy}
                  />
                  <T.Mesh
                    name="Object_11"
                    geometry={gltf.nodes.Object_11.geometry}
                    material={gltf.materials.full_glass}
                  />
                  <T.Mesh
                    name="Object_12"
                    geometry={gltf.nodes.Object_12.geometry}
                    material={gltf.materials.light_emit}
                  />
                  <T.Mesh
                    name="Object_13"
                    geometry={gltf.nodes.Object_13.geometry}
                    material={gltf.materials.flat_black}
                  />
                  <T.Mesh
                    name="Object_14"
                    geometry={gltf.nodes.Object_14.geometry}
                    material={gltf.materials.deep_black}
                  />
                  <T.Mesh
                    name="Object_15"
                    geometry={gltf.nodes.Object_15.geometry}
                    material={gltf.materials.door_knob}
                  />
                  <T.Mesh
                    name="Object_16"
                    geometry={gltf.nodes.Object_16.geometry}
                    material={gltf.materials.signal_light}
                  />
                  <T.Mesh
                    name="Object_17"
                    geometry={gltf.nodes.Object_17.geometry}
                    material={gltf.materials.windglass}
                  />
                  <T.Mesh
                    name="Object_18"
                    geometry={gltf.nodes.Object_18.geometry}
                    material={gltf.materials.gloss_black}
                  />
                  <T.Mesh
                    name="Object_19"
                    geometry={gltf.nodes.Object_19.geometry}
                    material={gltf.materials['Material.003']}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="Truck_body_Truck_bodyL_3"
                position={[-0.19, -0.46, -0.61]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1, 0.22, 0.75]}
              >
                <T.Mesh
                  name="Object_21"
                  geometry={gltf.nodes.Object_21.geometry}
                  material={gltf.materials.bodycolour}
                />
                <T.Mesh
                  name="Object_22"
                  geometry={gltf.nodes.Object_22.geometry}
                  material={gltf.materials.diffuse_black}
                />
                <T.Mesh name="Object_23" geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.door_knob} />
                <T.Mesh
                  name="Object_24"
                  geometry={gltf.nodes.Object_24.geometry}
                  material={gltf.materials.flat_black}
                />
                <T.Mesh
                  name="Object_25"
                  geometry={gltf.nodes.Object_25.geometry}
                  material={gltf.materials['signal_light.001']}
                />
                <T.Mesh
                  name="Object_26"
                  geometry={gltf.nodes.Object_26.geometry}
                  material={gltf.materials.full_glossy}
                />
                <T.Mesh
                  name="Object_27"
                  geometry={gltf.nodes.Object_27.geometry}
                  material={gltf.materials.gloss_black}
                />
                <T.Mesh name="Object_28" geometry={gltf.nodes.Object_28.geometry} material={gltf.materials.tyres} />
                <T.Mesh name="Object_29" geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.wheels} />
                <T.Mesh name="Object_30" geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.wheel_hub} />
                <T.Mesh
                  name="Object_31"
                  geometry={gltf.nodes.Object_31.geometry}
                  material={gltf.materials.deep_black}
                />
              </T.Group>
            </T.Group>
            <T.Group
              name="Empty012_7"
              position={[-1.35, -2.08, -7.45]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[1.73, 2.26, 2.26]}
            >
              <T.Group
                name="wheels_Circle001_5"
                position={[0.18, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_34"
                  geometry={gltf.nodes.Object_34.geometry}
                  material={gltf.materials['tyres.001']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle002_6"
                position={[0.29, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_36"
                  geometry={gltf.nodes.Object_36.geometry}
                  material={gltf.materials['wheels.001']}
                />
              </T.Group>
            </T.Group>
            <T.Group
              name="Empty011_10"
              position={[1.35, -2.08, -7.44]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[1.73, 2.26, 2.26]}
            >
              <T.Group
                name="wheels_Circle026_8"
                position={[-0.29, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_39"
                  geometry={gltf.nodes.Object_39.geometry}
                  material={gltf.materials['wheels.010']}
                />
              </T.Group>
              <T.Group
                name="wheels_Circle027_9"
                position={[-0.18, 0, 0]}
                rotation={[Math.PI / 2, 0, Math.PI]}
                scale={[1.3, 1, 1]}
              >
                <T.Mesh
                  name="Object_41"
                  geometry={gltf.nodes.Object_41.geometry}
                  material={gltf.materials['tyres.010']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
